(() => {
  "use strict";
  const root=document.documentElement,app=document.getElementById("app"),navBack=document.getElementById("nav-back"),navTitle=document.getElementById("nav-title"),themeToggle=document.getElementById("theme-toggle");
  const nf=new Intl.NumberFormat("zh-TW");let catalog=null;
  const isBetaPath=()=>/\/beta\/game-info\/?/.test(location.pathname);
  const mainSiteUrl=()=>isBetaPath()?"../../":"../";
  const currentPageId=()=>new URL(location.href).searchParams.get("page")||"";
  function setTheme(theme){theme==="dark"?root.setAttribute("data-theme","dark"):root.removeAttribute("data-theme");const dark=theme==="dark";themeToggle.textContent=dark?"☀️":"🌙";themeToggle.setAttribute("aria-label",dark?"切換至日間模式":"切換至夜間模式");themeToggle.setAttribute("aria-pressed",String(dark))}
  function initTheme(){let saved="light";try{saved=localStorage.getItem("msm-theme")==="dark"?"dark":"light"}catch(_){}setTheme(saved);themeToggle.addEventListener("click",()=>{const next=root.getAttribute("data-theme")==="dark"?"light":"dark";try{localStorage.setItem("msm-theme",next)}catch(_){}setTheme(next)})}
  async function fetchJson(path){const r=await fetch(path,{cache:"no-store"});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
  function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
  function setRoute(pageId,replace=false){const u=new URL(location.href);pageId?u.searchParams.set("page",pageId):u.searchParams.delete("page");history[replace?"replaceState":"pushState"]({},"",u);renderRoute()}
  function setNav(pageTitle=""){const detail=Boolean(pageTitle);navTitle.textContent=detail?pageTitle:"也許有用的資訊";navBack.textContent=detail?"資訊首頁":"主選單";navBack.onclick=detail?()=>setRoute(""):()=>{location.href=mainSiteUrl()}}
  const fmt=v=>v==null?"—":nf.format(v);
  function derivedRows(levels){return levels.map((level,index)=>{const next=levels[index+1]||null,prev=levels[index-1]||null;const coin=Number(level.upgradeCostAmount0||0)*Number(level.slotCount||0),unlock=[];if(index===0){unlock.push(`${level.slotCount} 個欄位`);unlock.push(`${level.presetCount} 組預設`)}else{if(Number(level.slotCount)>Number(prev.slotCount))unlock.push(`第 ${level.slotCount} 個欄位`);if(Number(level.presetCount)>Number(prev.presetCount))unlock.push(`第 ${level.presetCount} 組預設`)}if(!next)unlock.push("滿等");return{...level,expToNext:next?Number(next.needPoint)-Number(level.needPoint):null,expPerPray:Number(level.gainPoint||0)+Number(level.gainPointPerCoin||0)*coin,unlockText:unlock.length?(index===0?`初始：${unlock.join("・")}`:`開放 ${unlock.join("・")}`):"—",hasUnlock:unlock.length>0}})}
  function renderHome(){setNav("");document.title="也許有用的資訊｜楓之谷M 也許有用的工具";const rows=catalog.items.map(item=>{const ready=item.status==="ready";return `<button class="info-row" type="button" data-page="${esc(item.id)}" ${ready?"":"disabled"}><span class="info-icon" aria-hidden="true">${esc(item.icon)}</span><span class="info-copy"><span class="info-title">${esc(item.title)}</span><span class="info-subtitle">${esc(item.subtitle)}</span></span><span class="status-pill ${ready?"":"soon"}">${ready?"查看":"準備中"}</span></button>`}).join("");app.innerHTML=`<section class="glass-panel hero-compact"><div class="eyebrow">MapleStory M · Data Library</div><h2>也許有用的資訊</h2><p>遊戲內成長需求、等級門檻與系統資料。以簡單的一列式資訊為主，方便手機查詢與保存。</p></section><section class="info-list" aria-label="資訊分類">${rows}</section><div class="footer">Beta V7-R1 · Turbulence Smoke Root Fix。</div>`;app.querySelectorAll("[data-page]:not(:disabled)").forEach(b=>b.addEventListener("click",()=>setRoute(b.dataset.page)))}
  function renderDataRows(rows){return rows.map(r=>`<div class="data-row ${r.hasUnlock?"is-milestone":""}"><div class="data-cell data-level">Lv.${r.level}</div><div class="data-cell">${fmt(r.expToNext)}</div><div class="data-cell">${fmt(r.needPoint)}</div><div class="data-cell">${fmt(r.expPerPray)}</div><div class="data-cell data-unlock">${r.hasUnlock?`<span class="unlock-mark">${esc(r.unlockText)}</span>`:"—"}</div></div>`).join("")}
  async function renderLightSanctum(item){setNav(item.title);document.title=`${item.title}｜也許有用的資訊`;app.innerHTML=`<div class="glass-panel loading">正在載入資料…</div>`;try{const data=await fetchJson(item.data),rows=derivedRows(Array.isArray(data.levels)?data.levels:[]);if(!rows.length)throw new Error("找不到等級資料");const max=rows.at(-1);app.innerHTML=`<section class="glass-panel hero-compact"><div class="hero-line"><div><div class="eyebrow">Growth · Light Sanctum</div><h2>${esc(data.title)}</h2><p>Lv.1～Lv.${max.level} 升級經驗、累積 EXP、每次祈禱 EXP 與解鎖內容。</p></div><span class="source-chip">Client Table</span></div><div class="hero-actions"><button id="save-table-image" class="action-btn" type="button">儲存 / 分享表格圖片</button></div></section><section class="data-section" aria-label="光之聖所祈禱經驗表"><div class="liquid_glass-outer" aria-hidden="true"></div><div class="liquid_glass-cover" aria-hidden="true"></div><div class="liquid_glass-sharp" aria-hidden="true"></div><div class="liquid_glass-reflect" aria-hidden="true"></div><div class="data-header" aria-hidden="true"><div>等級</div><div>升下一級 EXP</div><div>累積 EXP</div><div>每次祈禱 EXP</div><div>解鎖內容</div></div>${renderDataRows(rows)}</section><section class="note-panel"><h3>資料說明</h3><p>「累積 EXP」直接對應 Client Table 的 <span class="code-inline">LevelInfo.needPoint</span>；「升下一級 EXP」由下一級 needPoint 減目前級 needPoint。</p><p>「每次祈禱 EXP」依正式模擬器公式 <span class="code-inline">GainPoint + GainPointPerCoin × CharacterCoin cost</span> 推導。Lv.${max.level} 為滿等，因此顯示 0。</p><p>「解鎖內容」由前後等級的欄位數與預設組數變化自動推導。來源：<span class="code-inline">${esc(data.source?.path||"")}</span>，資料版本 ${esc(data.updatedAt||"")}。</p></section><div class="footer">Beta V7-R1 · Turbulence Smoke Root Fix · 此頁只讀。</div>`}catch(e){app.innerHTML=`<div class="glass-panel error-box">資料載入失敗：${esc(e.message)}<br>請確認你是透過 GitHub Pages 網址開啟。</div>`}}
  async function renderRoute(){if(!catalog)return;const id=currentPageId();if(!id){renderHome();return}const item=catalog.items.find(x=>x.id===id&&x.status==="ready");if(!item){setRoute("",true);return}if(item.id==="light-sanctum-pray-exp"){await renderLightSanctum(item);return}renderHome()}
  async function init(){initTheme();app.innerHTML=`<div class="glass-panel loading">正在載入資訊中心…</div>`;try{catalog=await fetchJson("data/catalog.json");await renderRoute()}catch(e){setNav("");app.innerHTML=`<div class="glass-panel error-box">資訊中心載入失敗：${esc(e.message)}<br>請使用 GitHub Pages 測試網址開啟。</div>`}}
  addEventListener("popstate",renderRoute);init();
})();
